# Generated by Django 5.2.5 on 2025-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AlterField(
            model_name="trip",
            name="duration_trip",
            field=models.CharField(
                choices=[
                    ("1 day", "1 day"),
                    ("2-4 days", "2-4 days"),
                    ("5-7 days", "5-7 days"),
                    ("8-14 days", "8-15 days"),
                    (">14 days", ">14 days"),
                ],
                max_length=9,
            ),
        ),
    ]
