# Generated by Django 5.2.5 on 2025-08-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0002_alter_country_options_alter_trip_duration_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="reserved_seats",
        ),
    ]
