# Generated by Django 5.2.5 on 2025-08-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0003_remove_trip_reserved_seats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="author",
            new_name="author_trip",
        ),
    ]
