# Generated by Django 5.2.5 on 2025-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0004_rename_author_commentary_author_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
