# Generated by Django 5.2.5 on 2025-08-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0006_alter_rating_recipient_alter_triprequest_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
